defaults:
  - _self_

num_envs: 1
freq: 50 # can only be divisible by 200
camera_follow: True
#env_name: obstacle-dense
#env_name: hospital
#env_name: full-warehouse
env_name: matterport3d
episode_idx: 0

sensor:
  enable_lidar: True
  enable_camera: True
  color_image: True
  depth_image: True
  semantic_segmentation: True

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False

policy: WMP