defaults:
  - _self_
  - drone
  - ppo
  - sim

# headless: True
headless: False
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
env:
  num_envs: 10 # Number of drones for training
  max_episode_length: 2200
  env_spacing: 8.0 

env_dyn:
  num_obstacles: 200 # set to zero if static env is needed
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  # eye: [-38, 0.0, 50]
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: RL-Navigation
  name: env-code-clean
  entity: CERLAB-UAV-RL-Navigation
  mode: disabled # online
  # mode:  online
  run_id: #kw9xf9k9